runner:
  total_steps: 50000
  gradient_clipping: 1
  gradient_accumulate_steps: 1

  log_step: 10
  eval_step: 10
  save_step: 10
  max_keep: 1
  eval_dataloaders: 
    - dev
    - test
  
optimizer: 
  name: AdamW
  lr: 4.0e-4

# comment the whole scheduler config block to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1000

downstream_expert: 
  # we need to split data into three part
  datarc:
    train:
      file_path: /home/pohan/data/librispeech/vox2_dev/dev/aac
      utter_number: 2
      max_timestep: 80000
    test:
      file_path: /home/pohan/data/librispeech/vox1_test/wav
      meta_data: /home/pohan/data/librispeech/vox1_test/veri_test.txt
    dev:
      file_path: /home/pohan/data/librispeech/vox1_train_verifi/wav
      meta_data: /home/pohan/data/librispeech/vox1_train_verifi/valid_pairs_too_large.txt
      max_timestep: 128000
    train_batch_size: 2
    eval_batch_size: 1
    num_workers: 12

  modelrc: 
    input_dim: 256
    agg_module: SAP