runner:
  total_steps: 20000
  gradient_clipping: 1
  gradient_accumulate_steps: 5

  log_step: 100
  eval_step: 250
  save_step: 250
  max_keep: 1
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: AdamW
  lr: 2.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
scheduler:
  name: linear_schedule_with_warmup
  num_warmup_steps: 1400

downstream_expert:
  datarc:
    num_workers: 12
    train_batch_size: 3
    eval_batch_size: 3

  modelrc:
    input_dim: 256
