# dataset
roots: [
  '/home/leo/d/datasets/LibriSpeech/train-clean-100',
  '/home/leo/d/datasets/LibriSpeech/train-clean-360',
  '/home/leo/d/datasets/LibriSpeech/train-other-500',
]
sample_rate: 16000
max_time: 10000
target_level: -25
noise_proportion: 0.5
snrs: [3, 6]

# preprocessor
win_ms: 25
hop_ms: 10
n_freq: 201
n_mels: 40
n_mfcc: 13

# feature configuration
# feat_type can be: complx, linear, mel, mfcc, phase
input:
  feat_type: mel
  channel: 0
  log: True
  delta: 1
  cmvn: True
target:
  feat_type: linear
  channel: 1
  log: True
  delta: 0
  cmvn: False
