kaldi:
  # spectrogram, fbank, mfcc
  feat_type: fbank
  spectrogram:
    frame_length: 25.0
    frame_shift: 10.0
  fbank:
    num_mel_bins: 80
  mfcc:
    num_ceps: 13

delta:
  order: 2
  win_length: 5

cmvn:
  use_cmvn: True

